server:
  port: 8080

spring:
  application:
    name: spring-cloud-config

  cloud:
    config:
      server:
        git:
          #配置文件在github上的地址
          uri: https://github.com/gqzdev/spring-cloud-config.git
          username: gqzdev
          password:

          #Config  Server会在 Git仓库根目录、 foo子目录，
          # 以及所有以gqz开始的子目录中查找配置文件。
          search-paths: "gqz*"

          #启动时就clone仓库到本地，默认是在配置被首次请求时，
          #configserver才会clone git仓库
          clone-on-start: true

          #若配置中心在本地，本地的地址

#          native:#search-locations: classpath:/config

