# 通过Config配置中心 获取配置

server:
    port: 3000

spring:
    application:
        name: server-discover-eureka

#eureka配置
eureka:
    server:
        enable-self-preservation: true  # 自我保护机制  15分钟 超过85%
        eviction-interval-timer-in-ms: 4000  # 设置清理间隔 （单位： 毫秒 默认是60*1000）
    instance:
        hostname: localhost
#        hostname: eureka3000.com
#        statusPageUrlPath: ${server.servletPath}/info
#        healthCheckUrlPath: ${server.servletPath}/health

    client:
        serviceUrl:
            defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka
            # eureka集群配置  cluster
#            defaultZone: http://eureka3001.com:3001/eureka,http://eureka3002.com:3001/eureka
        # 此应用为注册中心，false：不向注册中心注册自己[默认为true]。
#        当搭建集群时，需要注册自己
        register-with-eureka: false
        # 注册中心职责是维护服务实例，false：不检索服务。
        fetch-registry: false