server:
    port: 5000

spring:
    application:
        name: client-user #此实例注册到eureka服务端的name


#eureka客户端配置  注册服务
eureka:
    client:
        serviceUrl:
            #eureka服务端提供的注册地址 参考服务端配置的这个路径
#            defaultZone: http://eureka3000.com:3000/eureka
            defaultZone: http://localhost:3000/eureka

    instance:
        instance-id: user-1 #此实例注册到eureka服务端的唯一的实例ID
        prefer-ip-address: true #是否显示IP地址
        #eureka客户需要多长时间发送心跳给eureka服务器，表明它仍然活着,默认为30 秒 (与下面配置的单位都是秒)
        leaseRenewalIntervalInSeconds: 10
        #Eureka服务器在接收到实例的最后一次发出的心跳后，需要等待多久才可以将此实例删除，默认为90秒
        leaseExpirationDurationInSeconds: 30

#feign  整合feign到hystrix中。默认是关闭的
feign:
    hystrix:
        enabled: true

#hystrix
hystrix:
    command:
        default:
            execution:
                isolation:
                    thread:
                        timeoutInMilliseconds: 30000
            # 配置熔断器设置  默认10秒
            circuitBreaker:
                requestVolumeThreshold: 5
#        sleepWindowInMilliseconds : 5000   时间


# 日志
#logging:
#    config: logback.xml
#    level:
#        com.gqzdev: trace

management:
    endpoints:
        web:
            exposure:
                include: "*"
# 开启actuator 端点